version: '3.8'

services:
  # Reverse Proxy
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      NETWORK: backend-network
      DEFAULT_HOST: mrbeas.net
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - backend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

  # SSL Certificate Manager
  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: millionmulugeta09@gmail.com
      ACME_CA_URI: https://acme-v02.api.letsencrypt.org/directory
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nginx-proxy
    networks:
      - backend-network
    restart: unless-stopped

  # Backend Services
  remi_server:
    container_name: remi_server
    image: millionmulugeta/remi_server:latest
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VIRTUAL_HOST=backend.mrbeas.net
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=backend.mrbeas.net
    expose:
      - 3000
    volumes:
      - ./remi_Backend:/app
      - /app/node_modules
    networks:
      - backend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

  mrb_backend:
    container_name: mrb_backend
    image: millionmulugeta/mrb_backend:latest
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VIRTUAL_HOST=dashboard-backend.mrbeas.net
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=dashboard-backend.mrbeas.net
      - TRUST_PROXY=1
    expose:
      - 3000
    volumes:
      - ./mrb_backend:/app
      - /app/node_modules
    networks:
      - backend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/system/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

  # Frontend Services
  mini_app:
    container_name: mini_app
    image: millionmulugeta/mini_app:latest
    environment:
      - NODE_ENV=production
      - PORT=80
      - VIRTUAL_HOST=app.mrbeas.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=app.mrbeas.net
    networks:
      - backend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

  dashboard:
    container_name: dashboard
    image: millionmulugeta/dashboard:latest
    env_file: .env
    networks:
      - backend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

  website:
    container_name: website
    image: millionmulugeta/website:latest
    environment:
      - NODE_ENV=production
      - PORT=80
      - VIRTUAL_HOST=mrbeas.net,www.mrbeas.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=mrbeas.net,www.mrbeas.net
    networks:
      - backend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  certs:
    driver: local
  vhost:
    driver: local
  html:
    driver: local

networks:
  backend-network:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.144.0/20
          gateway: 192.168.144.1