version: '3.8'

services:
  dashboard:
    image: millionmulugeta/dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard
    expose:
      - "3000"
    networks:
      - web_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dashboard
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

