version: '3.8'

services:
  dashboard:
    image: millionmulugeta/dashboard:latest
    container_name: dashboard
    restart: unless-stopped
    networks:
      - mrbeas_web_network
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_API_URL=https://backend-dashboard.mrbeas.net

  mrb_backend:
    image: millionmulugeta/mrb_backend:latest
    container_name: mrb_backend
    restart: unless-stopped
    networks:
      - mrbeas_web_network
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000

  caddy:
    image: caddy:2-alpine
    container_name: caddy_reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mrbeas_web_network
    depends_on:
      - dashboard
      - mrb_backend

volumes:
  caddy_data:
  caddy_config:

networks:
  mrbeas_web_network:
    driver: bridge