version: '3.8'

services:
  remi_server:
    container_name: remi_server
    image: millionmulugeta/remi_server:latest  
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 80
      VIRTUAL_HOST: api.glofica.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_ENABLED: "true"
      LETSENCRYPT_HOST: api.glofica.com
      LETSENCRYPT_EMAIL: millionmulugeta09@gmail.com
    volumes:
      - ./remi_Backend:/app   
      - /app/node_modules
    restart: unless-stopped
    networks:
      - backend-network
  mrb_backend:
    container_name: mrb_backend
    image: millionmulugeta/mrb_backend:latest  
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 80
      VIRTUAL_HOST: dashboard-backend.mrbeas.net
      VIRTUAL_PORT: 80
      LETSENCRYPT_ENABLED: "true"
      LETSENCRYPT_HOST: dashboard-backend.mrbeas.net
      LETSENCRYPT_EMAIL: millionmulugeta09@gmail.com
    volumes:
      - ./mrb_backend:/app   
      - /app/node_modules
    restart: unless-stopped
    networks:
      - backend-network

  mini_app:
    container_name: mini_app
    image: millionmulugeta/mini_app:latest
    environment:
      NODE_ENV: production
      PORT: 80
      VIRTUAL_HOST: frontend.mrbeas.net
      VIRTUAL_PORT: 80
      LETSENCRYPT_ENABLED: "true"
      LETSENCRYPT_HOST: frontend.mrbeas.net
      LETSENCRYPT_EMAIL: millionmulugeta09@gmail.com
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - backend-network

  dashboard:
    container_name: dashboard
    image: millionmulugeta/dashboard:latest
    environment:
      NODE_ENV: production
      PORT: 80
      VIRTUAL_HOST: wam.mrbeas.net
      VIRTUAL_PORT: 80
      LETSENCRYPT_ENABLED: "true"
      LETSENCRYPT_HOST: wam.mrbeas.net
      LETSENCRYPT_EMAIL: millionmulugeta09@gmail.com
    volumes:
      - ./dashboard/build:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    networks:
      - backend-network

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    environment:
      DEFAULT_EMAIL: millionmulugeta09@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    networks:
      - backend-network

volumes:
  certs:
  vhost:
  html:

networks:
  backend-network:
    driver: bridge 