version: '3.8'

services:
  dashboard:
    image: $DOCKERHUB_USERNAME/dashboard:latest
    container_name: dashboard_app
    restart: always
    expose:
      - "3000"

  mrb_backend:
    image: $DOCKERHUB_USERNAME/mrb_backend:latest
    container_name: mrb_backend
    restart: always
    expose:
      - "3000"

  mini_app:
    image: $DOCKERHUB_USERNAME/mini_app:latest
    container_name: mini_app
    restart: always
    expose:
      - "3000"

  remi_Backend:
    image: $DOCKERHUB_USERNAME/remi_Backend:latest
    container_name: remi_backend
    restart: always
    expose:
      - "3000"

  website:
    image: $DOCKERHUB_USERNAME/website:latest
    container_name: website_app
    restart: always
    expose:
      - "80"

  caddy:
    image: caddy:latest
    container_name: caddy_reverse_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - dashboard
      - mrb_backend
      - mini_app
      - remi_Backend
      - website

volumes:
  caddy_data:
  caddy_config: