version: '3.8'

services:
  dashboard:
    image: millionmulugeta/dashboard:latest
    container_name: dashboard
    restart: unless-stopped
    networks:
      - dashboard_mrbeas_web_network
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: dashboard_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    networks:
      - dashboard_mrbeas_web_network
    depends_on:
      dashboard:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:2019/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:

networks:
  dashboard_mrbeas_web_network:
    driver: bridge