version: '3.8'

services:
  dashboard:
    image: yourusername/dashboard:latest
    container_name: dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - mrbeas_web_network

  caddy_reverse_proxy:
    image: caddy:latest
    container_name: caddy_reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mrbeas_web_network

networks:
  mrbeas_web_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: